"""Categorized corporate lingo source data for ClarityLayer."""

from __future__ import annotations

from typing import Dict

LINGO_CATEGORIES: Dict[str, Dict[str, str]] = {
    "Strategy & Planning": {
        "north star": "Primary long-term goal.",
        "strategic alignment": "Plans support the same objective.",
        "move the needle": "Create meaningful improvement.",
        "double click": "Examine in more detail.",
        "double-click": "Examine in more detail.",
        "boil the ocean": "Take on too much at once.",
        "big rocks": "Highest-priority work.",
        "right-size": "Adjust to an appropriate level.",
        "level set": "Make sure everyone has shared context.",
        "northbound": "Direction toward top-level strategy.",
        "roadmap": "Sequenced plan over time.",
        "future state": "Target operating model after changes.",
        "current state": "How things work now.",
        "critical path": "Sequence of tasks that controls timeline.",
        "guiding principles": "Rules used to make decisions.",
        "scope creep": "Uncontrolled expansion of project scope.",
        "success criteria": "Clear outcomes that define success.",
        "value drivers": "Factors that produce most of the impact.",
        "priority matrix": "Framework for ranking importance and urgency.",
        "strategic pillar": "Major area of strategic focus.",
        "target operating model": "Design of future processes, roles, and systems.",
        "plan on a page": "One-page strategic summary.",
        "blue sky thinking": "Ideation without immediate constraints.",
        "scenario planning": "Preparation for multiple possible futures.",
        "long pole": "Greatest constraint in a timeline.",
        "decision framework": "Structured method for decision-making.",
        "portfolio view": "Cross-initiative perspective for priorities.",
        "strategic bet": "High-impact initiative with uncertainty.",
        "single-threaded owner": "One person with clear accountability.",
        "working backwards": "Start from desired outcome and plan steps in reverse.",
        "guardrails": "Boundaries that guide decisions while allowing autonomy.",
        "mission-critical": "Essential to business continuity or key outcomes.",
        "decision rights": "Clear ownership over who makes which decisions.",
    },
    "Communication & Meetings": {
        "circle back": "Follow up later.",
        "touch base": "Briefly connect.",
        "please advise": "Please provide guidance.",
        "for visibility": "Sharing for awareness.",
        "take this offline": "Discuss separately outside this meeting.",
        "socialize": "Share with stakeholders for feedback.",
        "quick sync": "Short coordination meeting.",
        "ping me": "Message me.",
        "parking lot": "Hold topic for later.",
        "align on": "Reach agreement on.",
        "let's huddle": "Hold a short focused meeting.",
        "close the loop": "Confirm completion and communicate outcome.",
        "action this": "Execute this task.",
        "as discussed": "Referencing prior conversation.",
        "follow-up": "Next communication after initial contact.",
        "deep dive": "Detailed review of a topic.",
        "offline review": "Review outside the live meeting.",
        "on the same page": "Shared understanding.",
        "table this": "Postpone this topic for now.",
        "open the kimono": "Share full details transparently.",
        "backchannel": "Side communication outside formal thread.",
        "bring this home": "Conclude and finalize this effort.",
        "ladder up": "Connect details to higher-level goals.",
        "cascade": "Communicate downward across teams.",
        "speak to": "Relate directly to a point.",
        "stay close": "Maintain frequent communication.",
        "land the message": "Ensure audience understands the point.",
        "sync up": "Coordinate with others.",
        "reach out": "Contact someone.",
        "connect offline": "Continue discussion outside current channel.",
        "takeaway": "Main conclusion or learning point.",
        "readout": "Structured summary of findings or status.",
        "pre-read": "Materials shared before a meeting for preparation.",
        "office hours": "Open time for ad-hoc questions or support.",
        "standing meeting": "Recurring meeting on a regular cadence.",
    },
    "Execution & Delivery": {
        "bandwidth": "Available capacity or time.",
        "low-hanging fruit": "Easy early wins.",
        "operationalize": "Put into standard process.",
        "run it up the flagpole": "Test idea with decision makers.",
        "push to production": "Release changes live.",
        "blocker": "Issue preventing progress.",
        "fast follow": "Planned follow-on work soon after launch.",
        "mvp": "Minimum viable product.",
        "quick win": "Early, visible improvement.",
        "workstream": "Organized track of related tasks.",
        "owner": "Person accountable for delivery.",
        "raci": "Responsibility assignment matrix.",
        "dependency": "Task/item required by another task.",
        "milestone": "Major checkpoint event.",
        "handoff": "Transfer work between teams.",
        "escalate": "Raise issue to higher authority.",
        "backlog": "Prioritized queue of pending work.",
        "deliverable": "Concrete output to be produced.",
        "runbook": "Documented operational procedures.",
        "playbook": "Repeatable approach for common scenarios.",
        "swimlane": "Role/department track in process flow.",
        "sprint": "Time-boxed delivery cycle.",
        "iteration": "One cycle of build-review-improve.",
        "go-live": "Production launch moment.",
        "postmortem": "Review after incident/project completion.",
        "root cause": "Underlying reason for an issue.",
        "triage": "Prioritize and sort issues quickly.",
        "cutover": "Transition from old to new system.",
        "rollback": "Revert to previous stable version.",
        "qa": "Quality assurance testing.",
        "war room": "Focused coordination forum for critical issues.",
        "cut scope": "Reduce scope to protect timelines or quality.",
        "ship date": "Target date for release or delivery.",
        "roll forward": "Apply a fix in a newer version rather than reverting.",
        "definition of done": "Agreed completion criteria for work.",
    },
    "Finance, Risk & Performance": {
        "kpi": "Key performance indicator.",
        "roi": "Return on investment.",
        "burn rate": "Rate of spending over time.",
        "headwinds": "External forces making progress harder.",
        "value-add": "Useful additional benefit.",
        "at risk": "Likely to miss target without intervention.",
        "cost-neutral": "No net increase in cost.",
        "run-rate": "Current rate projected over a period.",
        "variance": "Difference versus plan or baseline.",
        "red flag": "Warning signal requiring attention.",
        "budget envelope": "Maximum available budget.",
        "business case": "Justification for investment.",
        "sensitivity analysis": "Testing outcomes under different assumptions.",
        "unit economics": "Revenue/cost model per unit.",
        "forecast": "Expected future performance.",
        "margin": "Difference between revenue and cost.",
        "payback period": "Time required to recover investment.",
        "risk register": "Tracked list of risks and mitigations.",
        "mitigation": "Action to reduce risk impact.",
        "upside": "Potential positive outcome.",
        "downside": "Potential negative outcome.",
        "runway": "How long resources will last at current spend.",
        "cash burn": "Net cash outflow over time.",
        "cost center": "Function that incurs cost without direct revenue.",
        "profit center": "Unit responsible for direct revenue/profit.",
        "opex": "Operating expenses.",
        "capex": "Capital expenditures.",
        "gross margin": "Revenue minus direct costs ratio.",
        "ebitda": "Earnings before interest, taxes, depreciation, and amortization.",
        "baseline": "Reference point for measuring change.",
        "cost to serve": "Total cost required to support a customer or product.",
        "budget variance": "Difference between planned and actual spend.",
        "forecast accuracy": "How close projections are to actual outcomes.",
        "risk appetite": "Amount of risk an organization is willing to accept.",
        "risk trigger": "Signal that a risk is materializing.",
    },
    "Data, Tech & Product Acronyms": {
        "api": "Application programming interface.",
        "sdk": "Software development kit.",
        "etl": "Extract, transform, load.",
        "elt": "Extract, load, transform.",
        "sql": "Structured Query Language.",
        "nosql": "Non-relational data storage approach.",
        "sla": "Service level agreement.",
        "slo": "Service level objective.",
        "slis": "Service level indicators.",
        "rto": "Recovery time objective.",
        "rpo": "Recovery point objective.",
        "mttr": "Mean time to resolution.",
        "cicd": "Continuous integration and continuous delivery.",
        "feature flag": "Toggle to enable/disable functionality safely.",
        "observability": "Ability to understand system behavior from telemetry.",
        "data lineage": "Trace of data origin and transformations.",
        "db": "Database.",
        "ui": "User interface.",
        "ux": "User experience.",
        "sso": "Single sign-on.",
        "saml": "Security Assertion Markup Language.",
        "oauth": "Open authorization protocol.",
        "ci": "Continuous integration.",
        "cd": "Continuous delivery/deployment.",
        "cicd": "Automated integration and deployment pipeline.",
        "qa": "Quality assurance.",
        "uat": "User acceptance testing.",
        "prod": "Production environment.",
        "stg": "Staging environment.",
        "dev": "Development environment.",
        "poc": "Proof of concept.",
        "mvp": "Minimum viable product.",
        "okr": "Objectives and key results.",
        "sla": "Service level agreement.",
        "slo": "Service level objective.",
        "slm": "Service level management.",
        "sop": "Standard operating procedure.",
        "sme": "Subject matter expert.",
        "pm": "Project or product manager depending on context.",
        "tbd": "To be determined.",
        "tba": "To be announced.",
        "fyi": "For your information.",
        "eod": "End of day.",
        "eow": "End of week.",
        "qbr": "Quarterly business review.",
        "mbr": "Monthly business review.",
        "arr": "Annual recurring revenue.",
        "mrr": "Monthly recurring revenue.",
        "nps": "Net promoter score.",
        "csat": "Customer satisfaction score.",
        "cac": "Customer acquisition cost.",
        "ltv": "Lifetime value.",
        "churn": "Rate of customer loss.",
        "bom": "Bill of materials.",
        "erp": "Enterprise resource planning.",
        "crm": "Customer relationship management.",
        "hris": "Human resources information system.",
        "plg": "Product-led growth.",
        "abm": "Account-based marketing.",
        "seo": "Search engine optimization.",
        "sem": "Search engine marketing.",
        "ctr": "Click-through rate.",
        "cvr": "Conversion rate.",
    },
}

EXTRA_LINGO_CATEGORIES: Dict[str, Dict[str, str]] = {
    "Operations, Governance & People": {
        "run of show": "Detailed schedule and responsibilities for an event or initiative.",
        "single-threaded owner": "One clearly accountable owner for execution.",
        "decision log": "Record of key decisions and rationale.",
        "change request": "Formal request to alter scope, timeline, or cost.",
        "issue log": "Tracked list of open issues and owners.",
        "lessons learned": "Documented takeaways for future work.",
        "change management": "Structured approach to driving adoption.",
        "stakeholder mapping": "Identification of influence and impact groups.",
        "operating cadence": "Regular meeting and reporting rhythm.",
        "capacity planning": "Forecasting available resources for planned work.",
        "resource allocation": "Assigning people/budget to priorities.",
        "workforce planning": "Forecasting staffing needs.",
        "skills gap": "Difference between current and needed capabilities.",
        "cross-functional": "Involving multiple departments.",
        "handover": "Transfer of ownership or responsibilities.",
        "business continuity": "Ability to keep operations running during disruption.",
        "contingency plan": "Backup plan if risks materialize.",
        "escalation path": "Defined route for raising blockers.",
        "governance model": "Decision rights and accountability structure.",
        "operating model": "How the organization delivers value.",
        "span of control": "Number of direct reports per manager.",
        "org design": "Structure of roles and reporting lines.",
        "service desk": "Central support function for requests and incidents.",
        "sla breach": "Missed service-level commitment.",
        "incident response": "Coordinated approach to handling service disruptions.",
        "problem management": "Root-cause elimination process for recurring issues.",
        "knowledge base": "Repository of reusable documentation.",
        "standard work": "Documented best-practice process.",
        "process control": "Mechanisms to maintain consistent outcomes.",
        "compliance check": "Verification against policy or regulations.",
    },
    "General Corporate Words & Acronyms": {
        "ba": "Business analyst.",
        "brd": "Business requirements document.",
        "prd": "Product requirements document.",
        "sow": "Statement of work.",
        "msa": "Master services agreement.",
        "nda": "Non-disclosure agreement.",
        "rfp": "Request for proposal.",
        "rfi": "Request for information.",
        "rfq": "Request for quotation.",
        "kpi tree": "Hierarchical structure linking metrics to outcomes.",
        "north-star metric": "Primary metric indicating product/business health.",
        "b2b": "Business-to-business.",
        "b2c": "Business-to-consumer.",
        "gtm": "Go-to-market strategy.",
        "tam": "Total addressable market.",
        "sam": "Serviceable addressable market.",
        "som": "Serviceable obtainable market.",
        "moat": "Sustainable competitive advantage.",
        "win rate": "Percentage of opportunities won.",
        "pipeline": "Set of potential deals or initiatives in progress.",
        "close rate": "Percentage of opportunities that convert.",
        "bookings": "Value of signed contracts/orders.",
        "renewal": "Continuation of customer contract.",
        "upsell": "Selling a higher-tier product/service.",
        "cross-sell": "Selling additional products/services.",
        "cohort": "Group tracked over time by shared characteristic.",
        "run chart": "Trend line of performance over time.",
        "lead indicator": "Metric that predicts future outcomes.",
        "lag indicator": "Metric reflecting past performance.",
        "variance analysis": "Explaining differences between actuals and plan.",
    },
}

for category, terms in EXTRA_LINGO_CATEGORIES.items():
    LINGO_CATEGORIES.setdefault(category, {}).update(terms)



def flattened_lingo() -> Dict[str, str]:
    """Return all phrases in a single lowercase dictionary."""
    result: Dict[str, str] = {}
    for terms in LINGO_CATEGORIES.values():
        for phrase, translation in terms.items():
            result[phrase.strip().lower()] = translation.strip()
    return result


def phrase_category_lookup() -> Dict[str, str]:
    """Map each phrase to its category for display."""
    lookup: Dict[str, str] = {}
    for category, terms in LINGO_CATEGORIES.items():
        for phrase in terms:
            lookup[phrase.strip().lower()] = category
    return lookup
